name: CI/CD Test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    runs-on: - ubuntu-latest
             - research
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    
    - name: Run test_flow.py
      run: python test_flows.py